image: php:8.1.0-fpm

variables:
  XDEBUG_MODE: coverage

before_script:
  - apt-get -qq update
  - apt-get -qq install zip unzip -y
  - apt-get -qq install git libicu-dev libpq-dev libpng-dev libjpeg-dev libzip-dev libsqlite3-dev zlib1g-dev -y
  - pecl install xdebug && docker-php-ext-enable xdebug
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - composer require --dev phpunit/phpunit phpunit/php-code-coverage
  - composer global require "squizlabs/php_codesniffer=*"
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - echo "memory_limit=250M" >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini

stages:
  - Build
  - Code Quality
  - Test
  - Deploy

composer:
  stage: Build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - composer install
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/

Code Style:
  stage: Code Quality
  script:
    - vendor/bin/php-cs-fixer fix -vvv --dry-run --show-progress=dots
  except:
    - release
    - staging

Unused Dependencies Scanner:
  stage: Code Quality
  dependencies:
    - composer
  script:
    - vendor/bin/unused_scanner unused-scanner.php

Unit Test:
  stage: Test
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  dependencies:
    - composer
  script:
    - vendor/bin/phpunit --testdox --configuration phpunit.dist.xml
  artifacts:
    reports:
      junit:
        - build/phpunit/report.junit.xml
      coverage_report:
        coverage_format: cobertura
        path: build/phpunit/coverage.cobertura.xml
