image: php:8.3.0-fpm

variables:
  XDEBUG_MODE: coverage

before_script:
  - apt-get -qq update
  - apt-get -qq install zip unzip git libicu-dev libpq-dev libpng-dev libjpeg-dev libzip-dev libsqlite3-dev zlib1g-dev openssh-client -y
  - pecl install xdebug && docker-php-ext-enable xdebug
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - composer require --dev phpunit/phpunit phpunit/php-code-coverage
  - composer global require "squizlabs/php_codesniffer=*"
  - echo "memory_limit=250M" >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini

stages:
  - Build
  - Code Quality
  - Test
  - Release

composer:
  stage: Build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - composer install
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/

.test_template: &test_template
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  dependencies:
    - composer
  script:
    - vendor/bin/phpunit --testdox --configuration phpunit.dist.xml
  artifacts:
    reports:
      junit:
        - build/phpunit/report.junit.xml
      coverage_report:
        coverage_format: cobertura
        path: build/phpunit/coverage.cobertura.xml

Unit Test PHP 7.4:
  <<: *test_template
  stage: Test
  image: php:7.4-fpm

Unit Test PHP 8.0:
  <<: *test_template
  stage: Test
  image: php:8.0-fpm

Unit Test PHP 8.1:
  <<: *test_template
  stage: Test
  image: php:8.1-fpm

Unit Test PHP 8.2:
  <<: *test_template
  stage: Test
  image: php:8.2-fpm

Unit Test PHP 8.3:
    <<: *test_template
    stage: Test
    image: php:8.3-fpm

Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release job for $TAG"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'